name: CI/CD

on:
  push:
    branches: [main]

env:
  TARGET: wksp_free_edition  # Global variable

jobs:
  build:
    name: Build Python Wheel
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      # 4. Build wheel
      - name: Build wheel
        run: python -m build

      # 5. Upload wheel artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1   # equivalent to expire_in

      # 6. Upload repo files (for deploy/validate)
      - uses: actions/upload-artifact@v4
        with:
          name: repo
          path: .  # include all files
          retention-days: 1


  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest
    needs: build  # ensures build runs first
    steps:

      # 1. Download built wheel
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ${{ github.workspace }}/dist

      # 2. Download repo files (databricks.yml + others)
      - uses: actions/download-artifact@v4
        with:
          name: repo
          path: ${{ github.workspace }}
      
       # 3. Mask secrets
      - name: Mask personal information
        env:
          USER_EMAIL: ${{ secrets.DATABRICKS_USER_EMAIL }}
          USER_PATH: ${{ secrets.DATABRICKS_WORKSPACE_USER_PATH }}
        run: |
          echo "::add-mask::$USER_EMAIL"
          echo "::add-mask::$USER_PATH"

      # 4. Install Databricks CLI & SDK
      - name: Install Databricks CLI & SDK
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq unzip
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
          python -m pip install --upgrade pip
          pip install databricks-sdk

      # 5. Validate bundle
      - name: Run Databricks bundle validation
        env:
          TARGET: ${{ env.TARGET }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Validating wheel bundle..."
          ls
          databricks bundle validate --target $TARGET --profile $TARGET
        working-directory: ${{ github.workspace }}
